### ISSUE TITLE
Way to store the output in a text file

### ISSUE THREAD

**Issue by gautam678** [riedlma/topictiling#1]
Hello,
I'm testing this code with a text sample of mine and I am not able to save the output to a text file. My output is displayed in the terminal. Is there a way to have a parameter to store output to a directory?

![screen shot 2018-04-04 at 3 35 27 pm](https://user-images.githubusercontent.com/5861253/38330223-fdbf9784-381d-11e8-8041-98de1a94acad.png)

I have attached my output with this issue!

**Comment by gautam678** [comment]
To add more context: Say I'm processing two files. I want my output to be written into two files instead of one single file.

**Comment by riedlma** [comment]
Hi,
sorry for the late response. For some reason I did not receive any notification.
if you want the output be written into a file you can use the "-out" option. 
Creating a file for each processed file is currently not supported. But this could be easily done with a simple python script.

Best
Martin

**Comment by riedlma** [comment]
I've just created such a simple script:
https://github.com/riedlma/topictiling/blob/master/split_output.py

To run the script you require python and use the following parameters:

python split_output.py output_file_from_topictiling output_folder
