### ISSUE TITLE
what is  mode counting  in topicTiling means?

### ISSUE THREAD

**Issue by ZhengDeQuan** [riedlma/topictiling#3]
when runing the algorithm ,the hyperparameter m

[java]  -m       : Use mode counting (true/false) (default=true)

what is the mode counting means ? I 've read the papers , but i can't find something to answer my question.

**Comment by lxing532** [comment]
In the paper "TopicTiling: A Text Segmentation Algorithm based on LDA", it described the "counting mode". "True" means you draw block topic distribution from the word topicID driven from all the inference steps, "False" means you draw topic distribution from the word topicID driven from only the last inference step.

**Comment by lxing532** [comment]
> when runing the algorithm ,the hyperparameter m
> 
> [java] -m : Use mode counting (true/false) (default=true)
> 
> what is the mode counting means ? I 've read the papers , but i can't find something to answer my question.
In the paper "TopicTiling: A Text Segmentation Algorithm based on LDA", it described the "counting mode". "True" means you draw block topic distribution from the word topicID driven from all the inference steps, "False" means you draw topic distribution from the word topicID driven from only the last inference step.

**Comment by riedlma** [comment]
thanks for answering. For some reason, I have not seen/read that message. So sorry for the late response...

Without the "mode counting" a word has the topicId that was sampled in the last inference iteration.

When mode counting is enabled, all topicID assignments for each word are stored and the one that is sampled most is assigned to the word.

I will add some description in the README.md.

Best,
Martin

**Comment by riedlma** [comment]
description is added to the README.md file
